version: '3'

volumes:
  postgres_data:
      driver: local

networks:
  backend:
  frontend:

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      networks:
        - backend
  keycloak:
      image: jboss/keycloak
      environment:
        PROXY_ADDRESS_FORWARDING: "true"
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
      depends_on:
        - postgres
      networks:
        - backend
        - frontend

  nginx: 
      image: nginx:latest
      container_name: production_nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./nginx-selfsigned.crt:/common.crt
        - ./nginx-selfsigned.key:/common.key
      ports:
        - 80:80
        - 443:443
      networks:
        - frontend
      depends_on:
        - keycloak

